<a href="https://colab.research.google.com/github/ashmafee-iut/Image-Captioning/blob/main/Terms_For_Image_Caption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Points to be explored next:** 

 - reshape() on an image file

# **os.listdir()**
**os.listdir()** method in python is used to get the list of all files and directories in the specified directory. If we don’t specify any directory, then list of files and directories in the current working directory will be returned.

In [1]:
# Python program to explain os.listdir() method 
    
# importing os module 
import os
  
# Get the list of all files and directories
# in the root directory
path = "/"
dir_list = os.listdir(path)
  
print("Files and directories in '", path, "' :") 
  
# print the list
print(dir_list)

print(*dir_list, sep = "\n")

Files and directories in ' / ' :
['boot', 'mnt', 'opt', 'run', 'root', 'sys', 'var', 'home', 'bin', 'tmp', 'proc', 'srv', 'media', 'dev', 'lib64', 'usr', 'lib', 'etc', 'sbin', '.dockerenv', 'datalab', 'tools', 'content', 'python-apt', 'lib32', 'NGC-DL-CONTAINER-LICENSE']
boot
mnt
opt
run
root
sys
var
home
bin
tmp
proc
srv
media
dev
lib64
usr
lib
etc
sbin
.dockerenv
datalab
tools
content
python-apt
lib32
NGC-DL-CONTAINER-LICENSE


# **numpy_array.shape() AND numpy_array.reshape()**

# **Shape of an array:**

 - The shape of an array is the number of elements in each dimension.


**NumPy** arrays have an attribute called **shape** that returns a **tuple with each index** having the number of corresponding elements.

 > **Syntax:** numpy.shape(array_name) 

 > **Parameters:** Array is passed as a Parameter. 

 > **Return:** 
  - A **tuple** whose elements give the lengths of EACH corresponding array dimensions. 
  - **Integers** at **every index** tells about the number of elements the **corresponding dimension** has.
  - total number of indices indicates total number of dimensions of that array

In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

arr1 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
print(arr1.shape)

x = np.array([1, 2, 3, 4])
print(x.shape)

(2, 4)
(2, 4)
(4,)


In [22]:
y = np.zeros((2, 3, 4))
print(y.shape)
print(y)

print('-----------------------')
y.shape = (3, 8)
print(y)

# positons = (clus, row, col)

print('-----------------------')
y.shape = (2, 2, 3, 2)
print(y)

print('-----------------------')
arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr2)
print(arr2.shape)

(2, 3, 4)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----------------------
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
-----------------------
[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]
-----------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [21]:
# if shape is not matched with 24 elements 
y.shape = (3, 6)
print(y)

ValueError: ignored

Create an array with **5 dimensions** using **ndmin** using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [17]:
list1 = list(range(10))
arr = np.array(list1, ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[0 1 2 3 4 5 6 7 8 9]]]]]
shape of array : (1, 1, 1, 1, 10)


# **Reshaping**
 - **Reshaping** means changing the shape of an array.
   - The shape of an array is a tuple where each number represents the number of elements in each dimension.
 - Reshaping **numpy array** simply means changing the shape of the given array, 
  - by reshaping an array we can add or remove dimensions or change number of elements in each dimension.

 

 > Syntax : array.reshape(shape)

 > Parameters : It take tuple as argument, tuple is the new shape to be formed

 > Return : It returns numpy.ndarray

**Reshape From 1-D to 2-D**

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

print('-----------------------')
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-----------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Reshape From 1-D to 3-D**

In [30]:
arr = np.array(list(range(1,21)))

newarr = arr.reshape(2, 2, 5)
print(newarr)

print('-----------------------')

newarr = arr.reshape(4, 5)
print(newarr)

print('-----------------------')

newarr = arr.reshape(1, 4, 5)
print(newarr)

print('-----------------------')

newarr = arr.reshape(1, 1, 4, 5)
print(newarr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
-----------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
-----------------------
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]
-----------------------
[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]
   [16 17 18 19 20]]]]


In [33]:
import numpy as npy
 
# creating an array of 6 dimension
# using ndim
arr = npy.array([2, 4, 6, 8, 10], ndmin=6)
 
# printing array
print(arr)
 
# verifying the value of last dimension
# as 5
print('shape of an array :', arr.shape)
print(arr.shape[0], arr.shape[1], arr.shape[2], arr.shape[3], arr.shape[4], arr.shape[5])

[[[[[[ 2  4  6  8 10]]]]]]
shape of an array : (1, 1, 1, 1, 1, 5)
1 1 1 1 1 5


To transpose an array:

 > **syntax:** array.T

In [34]:
a = np.zeros((10, 2))
print(a)

# A transpose makes the array non-contiguous
b = a.T
print('-------------------------------')
print(b)

# Taking a view makes it possible to modify the shape without modifying
# the initial object.
c = b.view()
print('-------------------------------')
print(c)



[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
-------------------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
-------------------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


 > If **an integer**, then the result will be a **1-D array** of that length. Sometimes we pass (-1) as a parameter to flatten a multi-dimensional array into one-D array. 

 > One shape dimension can be **-1**. In this case, **the value is inferred from the length of the array and remaining dimensions**. -1 represents the unknown value which will be calculated from the remaining elements 
 
 - **Note:** We can not pass -1 to more than one dimension.

In [47]:
arr = np.array(list(range(1,21)))

newarr = arr.reshape(2, 2, -1)
print(newarr)

print('-----------------------')
newarr = arr.reshape(2, 2, 5)
print(newarr)

print('-----------------------')
newarr = arr.reshape(-1)
print(newarr)

print('-----------------------')
newarr = arr.reshape(20)
print(newarr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
-----------------------
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
-----------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
-----------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [49]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

print(arr.shape)

[1 2 3 4 5 6]
(6,)


In [51]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [53]:
np.sort(arr)

array([1, 2, 3, 4, 4, 4, 5])

Size of an array:
 > array.size

 > len(array)

In [54]:
arr.size

7

In [55]:
len(arr)


7